name: Generate Kafka Report

on:
  workflow_dispatch:

env:
  REPORT_FILE: "reports/kafka-utilization.csv"
  PROJECT_NAME: "kafka"

jobs:
  generate_report:
    name: Generate Report
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@v4
      - name: Build Gradle Project
        run: ./gradlew installDist -PacceptGradleTOS
      - name: Run API Queries
        run: build/install/develocity-runner-utilization/bin/develocity-runner-utilization --develocity-url="https://ge.apache.org"
        env:
          API_KEY: ${{ secrets.API_KEY }}
      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: kafka-utilization-csv
          path: ${{ env.REPORT_FILE }}